### ISSUE TITLE
Confusion about the output (role type)

### ISSUE THREAD

**Issue by ZacBi** [thunlp/HMEAE#4]
&emsp;&emsp;Hi, I have glanced through your paper and found the final output is the role type involved in the **input sentence** rather than the role type of **candidate entity**. Because you compress/encode the input embeddings to a sentence representation/embedding, then concatenate it with the role-oriented embedding before using a softmax to get the estimated role type.
&emsp;&emsp;Besides, what if there are no explicit argument roles in the daily text? I mean, you can't get labeled sentence in testset, so you don't know which role types contained in the input sentence. How could I calculate the role-oriented embedding?
&emsp;&emsp;Thank you for your explanation.

**Comment by wzq016** [comment]
entity information is included in dynamic maxpooling stage and the output is for candidate entity.

In test stage, we calculate every roles and select role with highest score, so we didn't use label in test stage.

**Comment by ZacBi** [comment]
&emsp;&emsp;Thanks for your response, but it doesn't clear my confusion. For your paper you said:

![image](https://user-images.githubusercontent.com/22130631/77042787-42fdf680-69f7-11ea-9a23-c50868c4fd96.png)

&emsp;&emsp;In `Logic Union Module` you calculate a **weighted average sum over all hidden states** in the sentence to get a role-oriented embedding(context vector for each role).
&emsp;&emsp;So, I understand that your method/framework can work if and only if **an input sentence contained one candidate entity**, otherwise it doesn't make sense. **Perhaps**, use dynamic max-pooling for each candidate entity to construct its own instance embedding x.

**Comment by wzq016** [comment]
Hidden embeddings **h** is related with selected trigger and entity, since we feed position embedding to encoder together with word embedding. So role-oriented embedding is related with candidate entity.

**Comment by ZacBi** [comment]
Fine... it looks like we don't reach the same point. I have to view your implementation before more discussions. Thank you again.
